# Generated by Django 3.0.8 on 2020-08-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naverwebtoon',
            name='img',
            field=models.URLField(max_length=2000, verbose_name='썸네일'),
        ),
        migrations.AlterField(
            model_name='naverwebtoon',
            name='link',
            field=models.URLField(max_length=2000, verbose_name='링크'),
        ),
        migrations.AlterField(
            model_name='naverwebtoon',
            name='title',
            field=models.TextField(verbose_name='타이틀'),
        ),
    ]
